### ISSUE TITLE
Screen size > 1024x768 renders black in larger area

### ISSUE THREAD

**Issue by jasonmayes** [CodeYellowBV/run-headless-chromium#2]
First off, this is awesome, thanks for the great work. I was trying to run this such that I could render at higher resolutions eg 1920x1200 but it appears if I dump a screenshot of the display chrome appears "black" at regions greater than 1024 in width and wont expand beyond the default size provided?

**Comment by Rob--W** [comment]
Try appending the `--window-size=width,height` flag to Chrome (where width and height are integers, smaller or equal to the dimensions passed to Xvfb). When I run Chrome without this flag, it would occasionally start in a smaller size, even if I enable kiosk mode via `--kiosk`. And use x24 instead of x32, it [appears that x32 is an invalid value](https://bugs.freedesktop.org/show_bug.cgi?id=17453).

Here is an example, without Node:

In some terminal, open a virtual display:
`Xvfb :1 -screen 0 1920x1200x24 -ac`

In another terminal, start Chrome, print the document size and close the window:
`DISPLAY=:1 /usr/lib/chromium/chromium --enable-logging=stderr  'data:text/html,<body onload="setTimeout(function(){console.log(innerWidth+&quot;x&quot;+innerHeight);close()},1000)">' --user-data-dir=/tmp/boooo --window-size=1920,1200`

The previous command shows that resizing the screen works:
`[9786:9786:0601/185307:INFO:CONSOLE(1)] "3839x1538", source: data:text/html,<body onload="setTimeout(function(){console.log(innerWidth+&quot;x&quot;+innerHeight);close()},1000)"> (1)`

**Comment by jasonmayes** [comment]
Ah super. I shall try that. Thanks for the reply
